disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional

included:
  - Sources

excluded:
  - build
  - DerivedData

line_length:
  warning: 120
  error: 150

identifier_name:
  min_length: 1

force_cast: warning
force_try: warning 